[package]
name = "rust-beanstalkd"
version = "0.2.0"
authors = ["Nicholas Dujay <nickdujay@gmail.com>"]

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-proto = "0.1"
combine = "2.2.2"
yaml-rust = "0.3.5"
clap = "~2.19.0"
